@echo off
echo Adding Tour Guide to all EMS pages...

REM Add tour guide button and scripts to all index pages
echo Processing Employee Management...
powershell -Command "(Get-Content 'resources\views\livewire\employee\employee-index.blade.php') -replace '<div>', '<div>@include(''components.tour-guide-button'')' | Set-Content 'resources\views\livewire\employee\employee-index.blade.php'"

echo Processing Attendance Management...
powershell -Command "(Get-Content 'resources\views\livewire\attendance\attendance-index.blade.php') -replace '<div>', '<div>@include(''components.tour-guide-button'')' | Set-Content 'resources\views\livewire\attendance\attendance-index.blade.php'"

echo Processing Leave Request Management...
powershell -Command "(Get-Content 'resources\views\livewire\leave-request\leave-request-index.blade.php') -replace '<div>', '<div>@include(''components.tour-guide-button'')' | Set-Content 'resources\views\livewire\leave-request\leave-request-index.blade.php'"

echo Processing Financial Request Management...
powershell -Command "(Get-Content 'resources\views\livewire\financial-request\financial-request-index.blade.php') -replace '<div>', '<div>@include(''components.tour-guide-button'')' | Set-Content 'resources\views\livewire\financial-request\financial-request-index.blade.php'"

echo Processing Daily Report Management...
powershell -Command "(Get-Content 'resources\views\livewire\daily-report\daily-report-index.blade.php') -replace '<div>', '<div>@include(''components.tour-guide-button'')' | Set-Content 'resources\views\livewire\daily-report\daily-report-index.blade.php'"

echo Processing Announcement Management...
powershell -Command "(Get-Content 'resources\views\livewire\announcement\announcement-index.blade.php') -replace '<div>', '<div>@include(''components.tour-guide-button'')' | Set-Content 'resources\views\livewire\announcement\announcement-index.blade.php'"

echo Processing Department Management...
powershell -Command "(Get-Content 'resources\views\livewire\department\department-index.blade.php') -replace '<div>', '<div>@include(''components.tour-guide-button'')' | Set-Content 'resources\views\livewire\department\department-index.blade.php'"

echo Processing Position Management...
powershell -Command "(Get-Content 'resources\views\livewire\position\position-index.blade.php') -replace '<div>', '<div>@include(''components.tour-guide-button'')' | Set-Content 'resources\views\livewire\position\position-index.blade.php'"

echo Processing Role Management...
powershell -Command "(Get-Content 'resources\views\livewire\role\role-index.blade.php') -replace '<div>', '<div>@include(''components.tour-guide-button'')' | Set-Content 'resources\views\livewire\role\role-index.blade.php'"

echo Processing Site Management...
powershell -Command "(Get-Content 'resources\views\livewire\site\site-index.blade.php') -replace '<div>', '<div>@include(''components.tour-guide-button'')' | Set-Content 'resources\views\livewire\site\site-index.blade.php'"

echo Processing Machine Management...
powershell -Command "(Get-Content 'resources\views\livewire\machine\machine-index.blade.php') -replace '<div>', '<div>@include(''components.tour-guide-button'')' | Set-Content 'resources\views\livewire\machine\machine-index.blade.php'"

echo Processing Project Management...
powershell -Command "(Get-Content 'resources\views\livewire\project\project-index.blade.php') -replace '<div>', '<div>@include(''components.tour-guide-button'')' | Set-Content 'resources\views\livewire\project\project-index.blade.php'"

echo Processing Visit Management...
powershell -Command "(Get-Content 'resources\views\livewire\visit\visit-index.blade.php') -replace '<div>', '<div>@include(''components.tour-guide-button'')' | Set-Content 'resources\views\livewire\visit\visit-index.blade.php'"

echo Processing Profile Management...
powershell -Command "(Get-Content 'resources\views\livewire\profile\profile-index.blade.php') -replace '<div>', '<div>@include(''components.tour-guide-button'')' | Set-Content 'resources\views\livewire\profile\profile-index.blade.php'"

echo Processing Settings Management...
powershell -Command "(Get-Content 'resources\views\livewire\setting\setting-index.blade.php') -replace '<div>', '<div>@include(''components.tour-guide-button'')' | Set-Content 'resources\views\livewire\setting\setting-index.blade.php'"

echo Processing Import Master Data...
powershell -Command "(Get-Content 'resources\views\livewire\import-master-data\import-master-data-index.blade.php') -replace '<div>', '<div>@include(''components.tour-guide-button'')' | Set-Content 'resources\views\livewire\import-master-data\import-master-data-index.blade.php'"

echo Processing Email Template Manager...
powershell -Command "(Get-Content 'resources\views\livewire\email-template-manager\email-template-manager-index.blade.php') -replace '<div>', '<div>@include(''components.tour-guide-button'')' | Set-Content 'resources\views\livewire\email-template-manager\email-template-manager-index.blade.php'"

echo Processing Reports...
powershell -Command "(Get-Content 'resources\views\livewire\report\report-index.blade.php') -replace '<div>', '<div>@include(''components.tour-guide-button'')' | Set-Content 'resources\views\livewire\report\report-index.blade.php'"

echo Processing Overtime Request Management...
powershell -Command "(Get-Content 'resources\views\livewire\overtime-request\overtime-request-index.blade.php') -replace '<div>', '<div>@include(''components.tour-guide-button'')' | Set-Content 'resources\views\livewire\overtime-request\overtime-request-index.blade.php'"

echo Processing Absent Request Management...
powershell -Command "(Get-Content 'resources\views\livewire\absent-request\absent-request-index.blade.php') -replace '<div>', '<div>@include(''components.tour-guide-button'')' | Set-Content 'resources\views\livewire\absent-request\absent-request-index.blade.php'"

echo Processing Activity Management...
powershell -Command "(Get-Content 'resources\views\livewire\activity\activity-index.blade.php') -replace '<div>', '<div>@include(''components.tour-guide-button'')' | Set-Content 'resources\views\livewire\activity\activity-index.blade.php'"

echo Processing Attendance Temp Management...
powershell -Command "(Get-Content 'resources\views\livewire\attendance-temp\attendance-temp-index.blade.php') -replace '<div>', '<div>@include(''components.tour-guide-button'')' | Set-Content 'resources\views\livewire\attendance-temp\attendance-temp-index.blade.php'"

echo Tour Guide has been added to all pages!
echo Please manually add @include('components.tour-guide-scripts') to the @push('js') section of each page.
pause
